# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.document_parsing_status_response_data import DocumentParsingStatusResponseData  # noqa: F401,E501
from swagger_server import util


class DocumentParsingStatusResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=None, data: DocumentParsingStatusResponseData=None, message: str=None):  # noqa: E501
        """DocumentParsingStatusResponse - a model defined in Swagger

        :param code: The code of this DocumentParsingStatusResponse.  # noqa: E501
        :type code: int
        :param data: The data of this DocumentParsingStatusResponse.  # noqa: E501
        :type data: DocumentParsingStatusResponseData
        :param message: The message of this DocumentParsingStatusResponse.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'code': int,
            'data': DocumentParsingStatusResponseData,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'data': 'data',
            'message': 'message'
        }
        self._code = code
        self._data = data
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentParsingStatusResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DocumentParsingStatusResponse of this DocumentParsingStatusResponse.  # noqa: E501
        :rtype: DocumentParsingStatusResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this DocumentParsingStatusResponse.


        :return: The code of this DocumentParsingStatusResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this DocumentParsingStatusResponse.


        :param code: The code of this DocumentParsingStatusResponse.
        :type code: int
        """

        self._code = code

    @property
    def data(self) -> DocumentParsingStatusResponseData:
        """Gets the data of this DocumentParsingStatusResponse.


        :return: The data of this DocumentParsingStatusResponse.
        :rtype: DocumentParsingStatusResponseData
        """
        return self._data

    @data.setter
    def data(self, data: DocumentParsingStatusResponseData):
        """Sets the data of this DocumentParsingStatusResponse.


        :param data: The data of this DocumentParsingStatusResponse.
        :type data: DocumentParsingStatusResponseData
        """

        self._data = data

    @property
    def message(self) -> str:
        """Gets the message of this DocumentParsingStatusResponse.


        :return: The message of this DocumentParsingStatusResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this DocumentParsingStatusResponse.


        :param message: The message of this DocumentParsingStatusResponse.
        :type message: str
        """

        self._message = message
