# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DocumentsParseBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, doc_ids: List[str]=None):  # noqa: E501
        """DocumentsParseBody - a model defined in Swagger

        :param doc_ids: The doc_ids of this DocumentsParseBody.  # noqa: E501
        :type doc_ids: List[str]
        """
        self.swagger_types = {
            'doc_ids': List[str]
        }

        self.attribute_map = {
            'doc_ids': 'doc_ids'
        }
        self._doc_ids = doc_ids

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentsParseBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The documents_parse_body of this DocumentsParseBody.  # noqa: E501
        :rtype: DocumentsParseBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def doc_ids(self) -> List[str]:
        """Gets the doc_ids of this DocumentsParseBody.


        :return: The doc_ids of this DocumentsParseBody.
        :rtype: List[str]
        """
        return self._doc_ids

    @doc_ids.setter
    def doc_ids(self, doc_ids: List[str]):
        """Sets the doc_ids of this DocumentsParseBody.


        :param doc_ids: The doc_ids of this DocumentsParseBody.
        :type doc_ids: List[str]
        """

        self._doc_ids = doc_ids
