# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DocumentDetails(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, location: str=None, size: int=None, type: str=None):  # noqa: E501
        """DocumentDetails - a model defined in Swagger

        :param id: The id of this DocumentDetails.  # noqa: E501
        :type id: str
        :param name: The name of this DocumentDetails.  # noqa: E501
        :type name: str
        :param location: The location of this DocumentDetails.  # noqa: E501
        :type location: str
        :param size: The size of this DocumentDetails.  # noqa: E501
        :type size: int
        :param type: The type of this DocumentDetails.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'location': str,
            'size': int,
            'type': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'location': 'location',
            'size': 'size',
            'type': 'type'
        }
        self._id = id
        self._name = name
        self._location = location
        self._size = size
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DocumentDetails of this DocumentDetails.  # noqa: E501
        :rtype: DocumentDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this DocumentDetails.


        :return: The id of this DocumentDetails.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this DocumentDetails.


        :param id: The id of this DocumentDetails.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this DocumentDetails.


        :return: The name of this DocumentDetails.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DocumentDetails.


        :param name: The name of this DocumentDetails.
        :type name: str
        """

        self._name = name

    @property
    def location(self) -> str:
        """Gets the location of this DocumentDetails.


        :return: The location of this DocumentDetails.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this DocumentDetails.


        :param location: The location of this DocumentDetails.
        :type location: str
        """

        self._location = location

    @property
    def size(self) -> int:
        """Gets the size of this DocumentDetails.


        :return: The size of this DocumentDetails.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this DocumentDetails.


        :param size: The size of this DocumentDetails.
        :type size: int
        """

        self._size = size

    @property
    def type(self) -> str:
        """Gets the type of this DocumentDetails.


        :return: The type of this DocumentDetails.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this DocumentDetails.


        :param type: The type of this DocumentDetails.
        :type type: str
        """

        self._type = type
