# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DocumentParsingStatusResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, progress: float=None, status: str=None):  # noqa: E501
        """DocumentParsingStatusResponseData - a model defined in Swagger

        :param progress: The progress of this DocumentParsingStatusResponseData.  # noqa: E501
        :type progress: float
        :param status: The status of this DocumentParsingStatusResponseData.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'progress': float,
            'status': str
        }

        self.attribute_map = {
            'progress': 'progress',
            'status': 'status'
        }
        self._progress = progress
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentParsingStatusResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DocumentParsingStatusResponse_data of this DocumentParsingStatusResponseData.  # noqa: E501
        :rtype: DocumentParsingStatusResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def progress(self) -> float:
        """Gets the progress of this DocumentParsingStatusResponseData.


        :return: The progress of this DocumentParsingStatusResponseData.
        :rtype: float
        """
        return self._progress

    @progress.setter
    def progress(self, progress: float):
        """Sets the progress of this DocumentParsingStatusResponseData.


        :param progress: The progress of this DocumentParsingStatusResponseData.
        :type progress: float
        """

        self._progress = progress

    @property
    def status(self) -> str:
        """Gets the status of this DocumentParsingStatusResponseData.


        :return: The status of this DocumentParsingStatusResponseData.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this DocumentParsingStatusResponseData.


        :param status: The status of this DocumentParsingStatusResponseData.
        :type status: str
        """

        self._status = status
