# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.list_documents_response_data import ListDocumentsResponseData  # noqa: F401,E501
from swagger_server import util


class ListDocumentsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=None, data: ListDocumentsResponseData=None, message: str=None):  # noqa: E501
        """ListDocumentsResponse - a model defined in Swagger

        :param code: The code of this ListDocumentsResponse.  # noqa: E501
        :type code: int
        :param data: The data of this ListDocumentsResponse.  # noqa: E501
        :type data: ListDocumentsResponseData
        :param message: The message of this ListDocumentsResponse.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'code': int,
            'data': ListDocumentsResponseData,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'data': 'data',
            'message': 'message'
        }
        self._code = code
        self._data = data
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ListDocumentsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListDocumentsResponse of this ListDocumentsResponse.  # noqa: E501
        :rtype: ListDocumentsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this ListDocumentsResponse.


        :return: The code of this ListDocumentsResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this ListDocumentsResponse.


        :param code: The code of this ListDocumentsResponse.
        :type code: int
        """

        self._code = code

    @property
    def data(self) -> ListDocumentsResponseData:
        """Gets the data of this ListDocumentsResponse.


        :return: The data of this ListDocumentsResponse.
        :rtype: ListDocumentsResponseData
        """
        return self._data

    @data.setter
    def data(self, data: ListDocumentsResponseData):
        """Sets the data of this ListDocumentsResponse.


        :param data: The data of this ListDocumentsResponse.
        :type data: ListDocumentsResponseData
        """

        self._data = data

    @property
    def message(self) -> str:
        """Gets the message of this ListDocumentsResponse.


        :return: The message of this ListDocumentsResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ListDocumentsResponse.


        :param message: The message of this ListDocumentsResponse.
        :type message: str
        """

        self._message = message
