# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuccessResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=None, data: bool=None, message: str=None):  # noqa: E501
        """SuccessResponse - a model defined in Swagger

        :param code: The code of this SuccessResponse.  # noqa: E501
        :type code: int
        :param data: The data of this SuccessResponse.  # noqa: E501
        :type data: bool
        :param message: The message of this SuccessResponse.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'code': int,
            'data': bool,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'data': 'data',
            'message': 'message'
        }
        self._code = code
        self._data = data
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessResponse of this SuccessResponse.  # noqa: E501
        :rtype: SuccessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this SuccessResponse.


        :return: The code of this SuccessResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this SuccessResponse.


        :param code: The code of this SuccessResponse.
        :type code: int
        """

        self._code = code

    @property
    def data(self) -> bool:
        """Gets the data of this SuccessResponse.


        :return: The data of this SuccessResponse.
        :rtype: bool
        """
        return self._data

    @data.setter
    def data(self, data: bool):
        """Sets the data of this SuccessResponse.


        :param data: The data of this SuccessResponse.
        :type data: bool
        """

        self._data = data

    @property
    def message(self) -> str:
        """Gets the message of this SuccessResponse.


        :return: The message of this SuccessResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this SuccessResponse.


        :param message: The message of this SuccessResponse.
        :type message: str
        """

        self._message = message
