# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.document_details import DocumentDetails  # noqa: F401,E501
from swagger_server import util


class UploadDocumentsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=None, data: List[DocumentDetails]=None, message: str=None):  # noqa: E501
        """UploadDocumentsResponse - a model defined in Swagger

        :param code: The code of this UploadDocumentsResponse.  # noqa: E501
        :type code: int
        :param data: The data of this UploadDocumentsResponse.  # noqa: E501
        :type data: List[DocumentDetails]
        :param message: The message of this UploadDocumentsResponse.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'code': int,
            'data': List[DocumentDetails],
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'data': 'data',
            'message': 'message'
        }
        self._code = code
        self._data = data
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'UploadDocumentsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UploadDocumentsResponse of this UploadDocumentsResponse.  # noqa: E501
        :rtype: UploadDocumentsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this UploadDocumentsResponse.


        :return: The code of this UploadDocumentsResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this UploadDocumentsResponse.


        :param code: The code of this UploadDocumentsResponse.
        :type code: int
        """

        self._code = code

    @property
    def data(self) -> List[DocumentDetails]:
        """Gets the data of this UploadDocumentsResponse.


        :return: The data of this UploadDocumentsResponse.
        :rtype: List[DocumentDetails]
        """
        return self._data

    @data.setter
    def data(self, data: List[DocumentDetails]):
        """Sets the data of this UploadDocumentsResponse.


        :param data: The data of this UploadDocumentsResponse.
        :type data: List[DocumentDetails]
        """

        self._data = data

    @property
    def message(self) -> str:
        """Gets the message of this UploadDocumentsResponse.


        :return: The message of this UploadDocumentsResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this UploadDocumentsResponse.


        :param message: The message of this UploadDocumentsResponse.
        :type message: str
        """

        self._message = message
