services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
      es01:
        condition: service_healthy
    image: infiniflow/ragflow_toyou:${RAGFLOW_VERSION}
    container_name: dangkangai-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 12141:80
      - 443:443
    volumes:
      - ./service_conf.yaml:/ragflow/conf/service_conf.yaml
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=https://huggingface.co
      - MACOS=${MACOS}
    env_file:
      - ./.env  # 添加env_file以加载环境变量
    networks:
      - ragflow
    restart: always

networks:
  ragflow:
    driver: bridge
