version: '3.1'

services:
  mysql:
    image: mysql:5.7.18
    container_name: mysql_rag_flow
    environment:
      MYSQL_ROOT_PASSWORD: infini_rag_flow
      MYSQL_DATABASE: rag_flow
      MYSQL_USER: root
      MYSQL_PASSWORD: infini_rag_flow
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
